package cn.mycar.enty;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.mycar.enty.UserEnty;

import cn.mycar.enty.UserEntyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userEntyDaoConfig;

    private final UserEntyDao userEntyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userEntyDaoConfig = daoConfigMap.get(UserEntyDao.class).clone();
        userEntyDaoConfig.initIdentityScope(type);

        userEntyDao = new UserEntyDao(userEntyDaoConfig, this);

        registerDao(UserEnty.class, userEntyDao);
    }
    
    public void clear() {
        userEntyDaoConfig.clearIdentityScope();
    }

    public UserEntyDao getUserEntyDao() {
        return userEntyDao;
    }

}
